### ISSUE TITLE
Running "mathicsscript FILE" gets "NameError: name 'FileLineFeeder' is not defined"

### ISSUE THREAD

**Issue by tueda** [Mathics3/mathicsscript#25]
As far as I understand from the help message, `mathicsscript FILE` corresponds to `wolframscript -f FILE`, which executes the file contents in `FILE`, but I got the following error:
```
$ mathicsscript test1.m
'/home/tueda/tmp/test-mathicsscript/.venv/lib/python3.8/site-packages/mathicsscript/settings.m' was not found.
Traceback (most recent call last):
  File "/home/tueda/tmp/test-mathicsscript/.venv/bin/mathicsscript", line 8, in <module>
    sys.exit(main())
  File "/home/tueda/tmp/test-mathicsscript/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tueda/tmp/test-mathicsscript/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tueda/tmp/test-mathicsscript/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tueda/tmp/test-mathicsscript/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tueda/tmp/test-mathicsscript/.venv/lib/python3.8/site-packages/mathicsscript/__main__.py", line 263, in main
    feeder = FileLineFeeder(file)
NameError: name 'FileLineFeeder' is not defined
```

<details><summary>Environment details</summary>
<p>

```
$ uname -a
Linux D************** 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

$ python3 --version
Python 3.8.7

$ mathicsscript --version
mathicsscript, version 2.0.0

$ cat test1.m
Print[1 + 2]

$ pip list
Package         Version
--------------- ---------
certifi         2020.12.5
chardet         4.0.0
click           7.1.2
colorama        0.4.4
columnize       0.3.10
cycler          0.10.0
decorator       4.4.2
idna            2.10
imageio         2.9.0
kiwisolver      1.3.1
llvmlite        0.35.0
Mathics-Scanner 1.0.0
Mathics3        2.0.0
mathicsscript   2.0.0
matplotlib      3.3.4
mpmath          1.2.1
networkx        2.5
numpy           1.20.1
packaging       20.9
palettable      3.3.0
Pillow          8.1.0
Pint            0.16.1
pip             20.2.3
Pygments        2.8.0
pyparsing       2.4.7
python-dateutil 2.8.1
PyWavelets      1.1.1
PyYAML          5.4.1
requests        2.25.1
scikit-image    0.18.1
scipy           1.6.1
setuptools      49.2.1
six             1.15.0
sympy           1.7.1
term-background 1.0.1
tifffile        2021.2.1
ujson           4.0.2
urllib3         1.26.3
wordcloud       1.8.1
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/home/tueda/tmp/test-mathicsscript/.venv/bin/python3.8 -m pip install --upgrade pip' command.
```

`mathicsscript` was installed in a virtual environment by `pip install mathicsscript`.

</p>
</details>

**Comment by tueda** [comment]
I've found that `mathics FILE` gives the same error:
```
$ mathics test1.m
Traceback (most recent call last):
  File "/home/tueda/tmp/test-mathicsscript/.venv/bin/mathics", line 8, in <module>
    sys.exit(main())
  File "/home/tueda/tmp/test-mathicsscript/.venv/lib/python3.8/site-packages/mathics/main.py", line 326, in main
    feeder = FileLineFeeder(args.FILE)
NameError: name 'FileLineFeeder' is not defined
```
